#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

CEYLON_HOME="${OPENSHIFT_REPO_DIR}.openshift/ceylon/"
CEYLON_REPO="${OPENSHIFT_RUNTIME_DIR}.ceylon-repo"

ceyonSrc="${OPENSHIFT_REPO_DIR}/src/main/ceylon/"

srcFiles=`find "${ceyonSrc}" -type f -name "*.ceylon" -print`
srcFilesInLine=`echo $srcFiles | tr '\n' ' '`

#create repo dir
if test \! -d "$CEYLON_REPO"
then
	mkdir $CEYLON_REPO
fi

${CEYLON_HOME}bin/ceylonc -src ${ceyonSrc} -rep ${CEYLON_REPO} -out ${CEYLON_REPO} ${srcFilesInLine} > ${OPENSHIFT_LOG_DIR}ceyon-build.log

