#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.
#OPENSHIFT_REPO_DIR="."

CEYLON_HOME="${OPENSHIFT_REPO_DIR}.openshift/ceylon/"

srcFiles=`find "${OPENSHIFT_REPO_DIR}/src/main/ceylon/" -type f -name "*.ceylon" -print`
srcFilesInLine=`echo $srcFiles | tr '\n' ' '`

${CEYLON_HOME}bin/ceylonc $srcFilesInLine > ${OPENSHIFT_LOG_DIR}ceyon-build.log
#echo "result: $srcFilesInLine"
