#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

CEYLON_HOME="${OPENSHIFT_REPO_DIR}.openshift/ceylon/"
CEYLON_REPO="${OPENSHIFT_RUNTIME_DIR}.ceylon-repo"

srcFiles=`find "${OPENSHIFT_REPO_DIR}/src/main/ceylon/" -type f -name "*.ceylon" -print`
srcFilesInLine=`echo $srcFiles | tr '\n' ' '`

${CEYLON_HOME}bin/ceylonc ${srcFilesInLine} -Dceylon.repo=${CEYLON_REPO}> ${OPENSHIFT_LOG_DIR}ceyon-build.log

